apiVersion: v2
name: hub
description: A Helm chart for Kubernetes
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "0.1.0"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

dependencies:
    -   name: mysql
        version: 11.1.15
        repository: https://charts.bitnami.com/bitnami

    -   name: redis
        version: 20.0.2
        repository: https://charts.bitnami.com/bitnami

    -   name: rabbitmq
        version: 14.6.6
        repository: https://charts.bitnami.com/bitnami

    -   name: authup-server-core
        repository: file://../authup-server-core
        version: 0.1.0

    -   name: hub-client-ui
        repository: file://../hub-client-ui
        version: 0.1.0

    -   name: hub-server-core
        repository: file://../hub-server-core
        version: 0.1.0
