apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-hub-server-core"
  labels:
    app: "{{ .Release.Name }}-hub-server-core"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-hub-server-core"
  template:
    metadata:
      name: "{{ .Release.Name }}-hub-server-core"
      labels:
        app: "{{ .Release.Name }}-hub-server-core"
    spec:
      initContainers:
          -   name: wait-for-db
              image: busybox
              command: [
                  'sh',
                  '-c',
                  'until nc -z -v -w30 {{ .Release.Name }}-hub-mysql-primary 3306; do echo "Waiting for db..."; sleep 5; done'
              ]
          -   name: wait-for-authup
              image: busybox
              command: [
                  'sh',
                  '-c',
                  'until nc -z -v -w30 {{ .Release.Name }}-authup-server-core 3000; do echo "Waiting for authup..."; sleep 5; done'
              ]
      containers:
        - name: "{{ .Release.Name }}-hub-server-core"
          image: "ghcr.io/privateaim/hub:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
              -   name: AUTHUP_URL
                  value: "http://{{ .Release.Name }}-authup-server-core:3000/"
              -   name: SKIP_PROJECT_APPROVAL
                  value: "true"
              -   name: SKIP_ANALYSIS_APPROVAL
                  value: "true"
              -   name: DB_TYPE
                  value: "mysql"
              -   name: DB_HOST
                  value: "{{ .Release.Name }}-hub-mysql-primary"
              -   name: DB_USERNAME
                  value: "root"
              -   name: DB_PASSWORD
                  value: "start123"
              -   name: DB_DATABASE
                  value: "core"
          resources:
              requests:
                  memory: "512Mi"
              limits:
                  memory: "2048Mi"
          readinessProbe:
              httpGet:
                  path: "/"
                  port: 3000
              initialDelaySeconds: 60
              periodSeconds: 5
              timeoutSeconds: 10
          livenessProbe:
              httpGet:
                  path: "/"
                  port: 3000
              periodSeconds: 10
              timeoutSeconds: 10
      restartPolicy: Always


