version: '3.9'
services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            interval: 3s
            timeout: 5s
            retries: 5
        environment:
            MYSQL_ROOT_PASSWORD: start123
        ports:
            - '3306:3306'
    redis:
        image: bitnami/redis
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
            interval: 3s
            timeout: 5s
            retries: 5
        ports:
            - '6379:6379'
    mq:
        image: bitnami/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 3s
            timeout: 5s
            retries: 5
        ports:
            - '5672:5672'
    vault:
        image: vault
        ports:
            - '8090:8090'
        healthcheck:
            test: [ "CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8090/v1/sys/health?standbyok=true" ]
            interval: 10s
            timeout: 3s
            retries: 10
            start_period: 5s
    authup:
        image: authup/authup
        depends_on:
            - mysql
            - redis
            - vault
        ports:
            - '3000:3010'
        environment:
            DB_TYPE: 'mysql'
            DB_USER: 'root'
            DB_PASSWORD: 'start'
            DB_DATABASE: 'auth'
            VAULT: start123@http://vault:8090/v1/
    serverCore:
        build: './Dockerfile'
        depends_on:
            - authup
            - mq
            - mysql
            - redis
            - vault
        ports:
            - '3000:3001'
        environment:
            REDIS_CONNECTION_STRING: redis://redis
            VAULT_CONNECTION_STRING: start123@http://vault:8090/v1/
            RABBITMQ_CONNECTION_STRING: amqp://root:start123@mq
            AUTHUP_API_URL: http://authup:3000/
            DB_TYPE: 'mysql'
            DB_USER: 'root'
            DB_PASSWORD: 'start'
            DB_DATABASE: 'core'

