# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
    push:
        branches: [develop, master, next, beta, alpha]
    pull_request:
        types: [ opened, synchronize ]

env:
    NODE_VERSION: 18
    NODE_REGISTRY: 'https://registry.npmjs.org'

jobs:
    main:
        services:
            authup:
                image: authup/authup
                ports:
                    - 3000:3000
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.PRIMARY_NODE_VERSION }}

            -   name: Build Core
                run: npm run build --workspace=packages/core

            -   name: Build Server Core
                run: npm run build --workspace=packages/server-kit

            -   name: Build Server Train Manager
                run: npm run build --workspace=packages/server-analysis-manager

            -   name: Build Server API
                run: npm run build --workspace=packages/server-api

            -   name: Test Server API
                env:
                    PORT: 4000
                    SKIP_PROPOSAL_APPROVAL_OPERATION: true
                    SKIP_TRAIN_APPROVAL_OPERATION: true
                    AUTHUP_API_URL: http://localhost:3000/
                run: |
                    npm run test --workspace=packages/server-api
